#!/bin/bash

# Source the bashrc file to get the MMC_APPLICATION_EXTENSION
. ../../../etc/bashrc

blockMesh
blockMesh -region super

topoSet
topoSet -region super

createPatch -overwrite
createPatch -overwrite -region super

blockMesh -region exMesh

cp system/itvInflowDict system/controlDict
itvInflow

cp system/mmcFoamDict system/controlDict

mmcFoam${MMC_APPLICATION_EXTENSION}

