#!/bin/bash

# Source the bashrc file to get the MMC_APPLICATION_EXTENSION
. ../../../etc/bashrc

blockMesh
blockMesh -region super

cp system/controlDict.1 system/controlDict

mmcRansFoam${MMC_APPLICATION_EXTENSION}

